### ISSUE TITLE
Assignment 02 ready for grading !

### ISSUE THREAD

**Issue by Erik9997** [SES-5215-F2020/erikfichter-quant#2]
Note: The purpose of my analysis is to draw lines between real estate values and in relation to the distance to work / the commute time. So far, looking at the data I figured out that I might have to use a different approach to see qualitative results. While I can read the value of properties the area is categorical and has a low accuracy so that it is hard to evaluate the value per area. Therefore I might go in the next week for a alternative direction looking at the rent prices instead as they reflect the value of an area in a similar manner. Also it would be required to patch the location of that residency with the same commute data together.

**Comment by saratepfer** [comment]
Thank you, Erik! nice job. Please see a few comments, below:

**Comments on Content**
- The descriptive statistics calculations are great, but it would be helpful if they were tabulated or formatted in some way that allowed the reader to more easily interpret them. As you currently have it in the HTML, the reader is left to parse through raw R output.
- Please provide some interpretation in addition to presenting your results (both for the descriptive statistics and the visualizations).

**Comments on Code**
- lines 255-261 and lines 171-177: You can adjust the angle of the text in your x-axis labels in your histograms by adding +theme(axis.text.x = element_text(angle = 45)) to each of the ggplot code chunks. This will prevent the labels from overlapping as they are now.
