### ISSUE TITLE
Assignment 03 ready for grading

### ISSUE THREAD

**Issue by Erik9997** [SES-5215-F2020/erikfichter-quant#3]

**Comment by saratepfer** [comment]
- line 7: replace {r} with {r, message = FALSE} to prevent r from printing unnecessary messages associated with loading your packages.
- If you would like to remove scientific notation from your graphs, insert the following line of code before your ggplot() entry: options(scipen = 999)
- Gross monthly rent v. travel time scatter plot: Please come by office hours to get this figured out. My instinct is that the problem has something to do with the rent variable, as it is printing as a decimal from -0.4 to 0.4 on your x-axis of your plot.
- Check your label location on your travel time to work v. means of transportation box plot.
- It would be great if you could expand your interpretation of the chi squared tests. It looks like each of the tests you ran show a statistically significant relationship. It would be great to see your interpretations of what you observe.
